import React from 'react';

interface OptimizedImageProps {
  src: string;                // Original filename e.g. "/ipalhotel.webp" or "ipalhotel.webp"
  alt: string;
  className?: string;
  width?: number;
  height?: number;
  /** true = hero/LCP images (no lazy, high priority). false = below-fold (lazy). Default: false */
  priority?: boolean;
  /** Extra sizes hint for srcset. Default: '(max-width: 640px) 480px, (max-width: 1024px) 800px, 1200px' */
  sizes?: string;
  referrerPolicy?: React.ImgHTMLAttributes<HTMLImageElement>['referrerPolicy'];
  style?: React.CSSProperties;
  onError?: React.ImgHTMLAttributes<HTMLImageElement>['onError'];
}

/**
 * OptimizedImage — drop-in replacement for <img> with:
 * - Automatic srcset using /img/sm/, /img/md/, /img/lg/ variants generated by optimize-images.mjs
 * - loading="lazy" for below-fold images (priority=false)
 * - fetchpriority="high" for hero/LCP images (priority=true)
 * - Explicit width/height to prevent Cumulative Layout Shift (CLS)
 */
export default function OptimizedImage({
  src,
  alt,
  className,
  width,
  height,
  priority = false,
  sizes = '(max-width: 640px) 480px, (max-width: 1024px) 800px, 1200px',
  referrerPolicy = 'no-referrer',
  style,
  onError,
}: OptimizedImageProps) {
  const filename = src.startsWith('/') ? src.slice(1) : src;
  const isWebp = filename.endsWith('.webp');

  const useOptimized = isWebp && !filename.startsWith('img/') && !filename.startsWith('fonts/');

  const srcSet = useOptimized
    ? '/img/sm/' + filename + ' 480w, /img/md/' + filename + ' 800w, /img/lg/' + filename + ' 1200w'
    : undefined;

  const optimizedSrc = useOptimized ? '/img/lg/' + filename : src;

  return (
    <img
      src={optimizedSrc}
      srcSet={srcSet}
      sizes={srcSet ? sizes : undefined}
      alt={alt}
      className={className}
      width={width}
      height={height}
      loading={priority ? 'eager' : 'lazy'}
      // fetchPriority is not in React types for older TS, use any cast trick
      {...(priority ? { fetchPriority: 'high' } : {})}
      decoding={priority ? 'sync' : 'async'}
      referrerPolicy={referrerPolicy}
      style={style}
      onError={onError}
    />
  );
}
